# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-962f60f3-7e95-4836-a625-b08c48d01bbc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-962f60f3-7e95-4836-a625-b08c48d01bbc".device = "/dev/disk/by-uuid/962f60f3-7e95-4836-a625-b08c48d01bbc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/20F8-6E48";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2c6ea7a5-caed-49dd-b227-7032fe7cff06"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
